apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: php-sf-template
  annotations:
    description: "A common way for creating php App ."
    iconClass: "icon-php"
    tags: "php,symfony"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${DEPLOYMENT_NAME}
    labels:
      app: ${APP_LABEL}
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: ${APP_LABEL}
    template:
      metadata:
        labels:
          app: ${APP_LABEL}
      spec:
        containers:
        - name: ${APP_LABEL}
          image: symfonypower/free-sf-app:1.0.0
          ports:
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: ${SERVICE_LABEL}
  spec:
    selector: 
      app: ${APP_LABEL}
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${ROUTE_NAME}
  spec:
    host: ${ROUTE_NAME}-sowboy-red-hat-dev.apps.sandbox.x8i5.p1.openshiftapps.com
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${SERVICE_LABEL}
parameters:
- description: "The name of the deployment"
  displayName: "DEPLOYMENT_NAME"
  name: DEPLOYMENT_NAME
- description: "The name of the service"
  displayName: "SERVICE_LABEL"
  name: SERVICE_LABEL
- description: "The name of the route"
  displayName: "ROUTE_NAME"
  name: ROUTE_NAME
- description: "The name of the app"
  displayName: "APP_NAME"
  name: APP_LABEL




